name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Setup clasp auth (service account)
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
          mkdir -p ~/.config
          echo '{
            "token": {
              "type": "service_account",
              "private_key": $(jq -r '.private_key' credentials.json | sed 's/\\n/\\n/g'),
              "client_email": $(jq -r '.client_email' credentials.json)
            },
            "scriptId": "${{ secrets.SCRIPT_ID }}"
          }' > ~/.clasprc.json

      - name: Replace GitHub Token in code
        run: |
          find src -type f -name "*.js" -print0 | xargs -0 sed -i 's|<<GITHUB_TOKEN>>|${{ secrets.GH_TOKEN }}|g'

      - name: Push to Apps Script
        run: clasp push --force
