name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        run: |
          cat << 'EOF' > ~/.clasprc.json
          ${{ secrets.CLASP_CREDENTIALS }}
          EOF

          cat << 'EOF' > .clasp.json
          ${{ secrets.CLASP_PROJECT }}
          EOF

      - name: Debug JSON
        run: |
          cat ~/.clasprc.json
          cat .clasp.json

      - name: Push to Apps Script
        run: clasp push --force

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get access token
        id: auth
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo "token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Set GITHUB_TOKEN property in Apps Script
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
            -H "Content-Type: application/json" \
            "https://script.googleapis.com/v1/projects/141P-4LIY2KuL1rwIamUUk8I2aL1g0xaKJikybLtHQ4ceBfH65Uvlu7jX/properties" \
            -d '{
              "properties": {
                "GITHUB_TOKEN": "'"${{ secrets.GH_TOKEN }}"'"
              }
            }'