name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        run: |
          cat << 'EOF' > ~/.clasprc.json
          ${{ secrets.CLASP_CREDENTIALS }}
          EOF

          cat << 'EOF' > .clasp.json
          ${{ secrets.CLASP_PROJECT }}
          EOF

      - name: Debug JSON
        run: |
          cat ~/.clasprc.json
          cat .clasp.json

      - name: Push to Apps Script
        run: clasp push --force

      - name: Install triggers
        run: clasp run setupTriggers